import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#004c69",
        tertiary: "#7bd0ff",
        "error-container": "#93000a",
        "primary-fixed": "#e9ddff",
        "on-tertiary-container": "#002d40",
        "inverse-on-surface": "#2e303a",
        outline: "#958ea0",
        "primary-fixed-dim": "#d0bcff",
        surface: "#11131c",
        primary: "#d0bcff",
        "on-error": "#690005",
        "outline-variant": "#494454",
        "inverse-surface": "#e2e1ef",
        "secondary-fixed-dim": "#ffb0cd",
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "tertiary-fixed-dim": "#7bd0ff",
        "surface-container": "#1d1f29",
        "surface-container-low": "#191b24",
        "on-primary-fixed-variant": "#5516be",
        "primary-container": "#a078ff",
        "on-secondary": "#640039",
        "on-primary-fixed": "#23005c",
        "on-background": "#e2e1ef",
        "surface-container-lowest": "#0c0e17",
        "on-surface-variant": "#cbc3d7",
        "surface-variant": "#33343e",
        "surface-bright": "#373943",
        "surface-container-highest": "#33343e",
        "tertiary-fixed": "#c4e7ff",
        "on-secondary-fixed": "#3e0022",
        error: "#ffb4ab",
        "secondary-fixed": "#ffd9e4",
        "surface-container-high": "#282933",
        "on-surface": "#e2e1ef",
        "secondary-container": "#aa0266",
        "tertiary-container": "#009bd1",
        background: "#11131c",
        "surface-dim": "#11131c",
        "on-tertiary-fixed": "#001e2c",
        "on-error-container": "#ffdad6",
        secondary: "#ffb0cd",
        "inverse-primary": "#6d3bd7",
        "surface-tint": "#d0bcff",
        "on-tertiary": "#00354a",
        "on-secondary-container": "#ffbad3",
        "on-secondary-fixed-variant": "#8c0053",
        spaceBg: "#05020a",
        glassBg: "rgba(13, 8, 28, 0.55)",
        neonPink: "#ff4b91",
        neonPurple: "#a855f7",
        cosmicBlue: "#6366f1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        gutter: "24px",
        "stack-lg": "32px",
        "stack-xl": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-geist)", "Geist", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
      boxShadow: {
        panel: "0 10px 30px rgba(15, 23, 42, 0.08)",
        "glow-pink": "0 0 25px rgba(255, 75, 145, 0.4)",
        "glow-purple": "0 0 30px rgba(168, 85, 247, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
